# Generated by Django 5.0.6 on 2024-06-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('ca', models.IntegerField()),
                ('exams', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
