# Generated by Django 5.0.6 on 2024-06-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
