# Generated by Django 5.0.6 on 2024-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_coordinator',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
