# Generated by Django 5.0.6 on 2024-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_course_course_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('registration_number', models.CharField(max_length=20)),
                ('registration_course', models.CharField(max_length=20)),
                ('entry_fee', models.IntegerField()),
                ('current_semester', models.IntegerField()),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
