# Generated by Django 5.0.6 on 2024-06-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student', to='members.course'),
        ),
    ]
