# Generated by Django 5.0.6 on 2024-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_home_remove_student_courses_delete_grades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('joined_date', models.DateField()),
            ],
        ),
    ]
