# Generated by Django 5.0.6 on 2024-06-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
